version: '3'
services:
    todo:
        build: ./todo/
        volumes:
            - "./todo/application:/app"
        ports: 
            - "8000:8000"
        command: "/bin/sh /app/entrypoint-dev"
        env_file:
            - "./todo/todo.env"
        depends_on:
            - db
    db:
        image: "postgres:alpine"
        volumes:
            - "postgres_data:/var/lib/postgresql/data/"
        environment:
            - POSTGRES_USER=hello_django
            - POSTGRES_PASSWORD=hello_django
            - POSTGRES_DB=hello_django_dev
    vue:
        build: ./todo_vue/
        ports:
            - "8080:8080"
        volumes:
            - "./todo_vue/application:/app"
            - "/app/node_modules"
        depends_on:
            - todo
volumes:
    postgres_data:

